title: "PHẦN 3: TÀI CHÍNH VÀ LỢI ÍCH KINH TẾ TỪ TÍN CHỈ CARBON"
icon: false
items:
  - 01.what-price-usd-credit-can-sme-enterprises-expect-for-selling-carbon-credits
  - 02.what-green-credit-options-are-being-offered-by-domestic-banks-such-as-bidv-and-vietinbank
  - 03.can-enterprises-receive-tax-exemptions-reductions-if-they-implement-emission-reduction-projects
  - 04.can-carbon-credits-be-used-as-collateral-mortgage-for-loans
  - 05.how-should-smes-plan-costs-for-mrv-activities
  - 06.what-are-the-financial-risks-that-smes-need-to-be-aware-of-e-g-price-volatility-increased-verifi
  - 07.can-businesses-access-blended-finance-from-the-international-finance-corporation-ifc-the-world-b
  - 08.how-to-value-co-benefits-such-as-contributions-to-sustainable-development-goals-sdgs-or-biodiver
  - 09.can-carbon-credits-help-smes-cope-with-the-european-unions-carbon-border-adjustment-mechanism-cb