title: "PART 1: CONCEPTS AND LEGAL DOCUMENTS RELATED TO CARBON CREDITS"
icon: false
items:
  - 00.acknowledge
  - 01.what-is-a-carbon-credit
  - 02.what-are-compliance-and-voluntary-carbon-markets
  - 03.what-is-mrv-and-why-is-it-important
  - 04.important-international-legal-instruments-related-to-carbon-credits
  - 05.vietnamese-legal-documents-related-to-the-carbon-market
  - 06.common-carbon-credit-standards-mechanisms-currently-applied
  - 07.how-does-the-voluntary-carbon-market-differ-from-the-pilot-emission-trading-system-ets-in-vietna
  - 08.when-will-the-ets-market-officially-operate-in-vietnam
  - 09.which-exchange-will-enterprises-use-to-trade-carbon-credits-can-they-trade-through-the-hanoi-sto
  - 10.how-do-carbon-credits-and-emission-quotas-differ
  - 11.can-vietnam-connect-carbon-credits-with-the-international-market-through-mechanisms-such-as-cdm
  - 12.if-an-enterprise-exceeds-the-permitted-emission-level-in-the-ets-how-will-it-be-handled
