title: "PART 2: FROM EMISSION CALCULATION TO IMPLEMENTATION OF EMISSION REDUCTION PROJECTS"
icon: false
items:
  - 01.how-does-an-sme-calculate-its-total-greenhouse-gas-emissions-carbon-footprint
  - 02.which-emission-factors-should-sme-enterprises-use-that-are-suitable-for-conditions-in-vietnam
  - 03.is-indirect-emissions-in-the-supply-chain-scope-3-mandatory-to-calculate-should-smes-calculate-i
  - 04.can-enterprises-in-different-sectors-use-sector-specific-emission-factors
  - 05.methodological-database-of-verified-carbon-standard-vcs-and-gold-standard
  - 06.what-low-cost-emission-reduction-solutions-are-suitable-for-smes-in-vietnam
  - 07.what-documents-and-certifications-are-necessary-to-prove-a-project-is-eligible-for-carbon-credit
  - 08.can-smes-jointly-implement-a-common-project-to-share-the-costs-of-measurement-reporting-and-veri
  - 09.how-long-does-it-usually-take-for-a-project-to-be-registered-verified-and-issued-carbon-credits
  - 10.what-is-the-specific-mrv-process-according-to-the-guidance-of-the-ministry-of-agriculture-and-en
