title: "PHẦN 5: QUẢN TRỊ RỦI RO, MINH BẠCH VÀ THỰC HÀNH TỐT"
icon: false
items:
  - 01.how-to-avoid-greenwashing-and-ensure-project-credibility
  - 02.what-is-the-criterion-for-assessing-additionality-in-a-project
  - 03.what-happens-if-a-project-fails-to-achieve-the-committed-emission-reduction-targets
  - 04.how-to-control-the-risk-of-leakage-and-ensure-permanence
  - 05.what-is-vietnam-doing-to-prevent-double-counting
  - 06.how-should-sme-businesses-react-if-ets-regulations-change-suddenly
  - 07.what-mechanisms-ensure-transparency-when-registering-and-trading-carbon-credits
  - 08.how-to-demonstrate-co-benefits-social-ecosystem-to-attract-investors
  - 09.what-governance-principles-should-smes-follow-to-ensure-transparency-throughout-the-entire-cycle